### ISSUE TITLE
error on docker build

### ISSUE THREAD

**Issue by 4rutnv3g** [docker-exec/lua#1]
Hi there

On running `sudo docker build github.com/docker-exec/lua.git` I received the following output including an error message:

```
Sending build context to Docker daemon  168.4kB
Step 1/7 : FROM        debian:8.0
8.0: Pulling from library/debian
e5ad7970bc69: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:6dfae856bbe10122a417356da295380a926e81f745bd45d5a41ad354bd19b4b1
Status: Downloaded newer image for debian:8.0
 ---> d82f599287cd
Step 2/7 : MAINTAINER  andystanton
 ---> Running in 14e0f7fd6237
Removing intermediate container 14e0f7fd6237
 ---> 10a5d9b824a1
Step 3/7 : ENV         LANG C.UTF-8
 ---> Running in c0b63e5d9be1
Removing intermediate container c0b63e5d9be1
 ---> 46db1edbf1c1
Step 4/7 : RUN         apt-get update -qq && apt-get install -y patch lua5.2
 ---> Running in 1fff16a3ced7
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update -qq && apt-get install -y patch lua5.2' returned a non-zero code: 100
```

I am just starting out with docker so quite possibly this is entirely my error, just thought I'd let you know in case there is an issue here for you.

Cheers

**Comment by andystanton** [comment]
Thanks for the report @4rutnv3g! These images are very old now and I need to update them all.

To help you out getting started with Docker, here's a minimal Dockerfile that contains lua:

```
FROM alpine:latest
RUN apk update && apk add lua5.3
ENTRYPOINT ["lua5.3"]
```

Save that as a `Dockerfile` somewhere then run this from that path:

```
docker build -t lua-test .
```

You can then run the image and pass scripts to it directly like this:

```
docker run -it --rm lua-test -e 'print("hello world")'
```

or mount scripts into the running container and evaluate them like this:

```
docker run -it --rm -v $PWD/foo.lua:/foo.lua lua-test /foo.lua
```

Hope that helps - I'm going to close this issue because for dexec's purposes the images don't need to be rebuilt, and there are a few related issues open in the dexec CLI repo: docker-exec/dexec#40, docker-exec/dexec#45 & docker-exec/dexec#62.

Good luck with your learning!
